### ISSUE TITLE
Cannot handle "(no branch)"

### ISSUE THREAD

**Issue by wew036** [SethRobertson/git-what-branch#1]
This script cannot handle the case where git outputs "\* (no branch)":

$ git-what-branch f142dd53
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0:`git rev-list -n 1 (no branch) 2>/dev/null'
Unknown --reference (no branch)

**Comment by SethRobertson** [comment]
Should be resolved in version 0.2.2.  Thanks for the bug report.
